Adding Lxml pip dependency for de-obfuscation scripts required by some indexers
linuxserver/docker-nzbget pull request #120
Opened 2020-11-22 07:38 UTC by tylergibson

Adding the lxml pip package for python scripts

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [ X] I have read the [contributing](https://github.com/linuxserver/docker-nzbget/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
Adding the lxml pip package for python scripts

## Benefits of this PR and context:
Some indexers have begun obfuscating file names in NZBs, requiring new scripts to parse NZBs and decode filenames from the xml metadata.  These scripts have a dependency on lxml.
While currently limited in affected indexers, other nzb binary downloaders have patched to handle this.
This will likely become more pervasive with time.

## How Has This Been Tested?
custom docker build on personal Unraid 6.8.2

2020-12-20 00:48 UTC, tylergibson commented
@nemchik - thoughts?

2020-12-20 01:01 UTC, nemchik requested changes
I don't mind this being added, but it doesn't seem to match the indentation of the others

2021-01-08 18:04 UTC, tylergibson commented
@nemchik - I double checked and rebased to current master, but the indentation lines up on both web and local?

2021-02-01 22:00 UTC, Roxedus commented
These *scripts*, are they bundled in NZBGet?

2021-02-02 16:34 UTC, nemchik approved these changes

2021-02-02 16:34 UTC, merged